namespace Barotrauma.LuaCs.Data;

/// <summary>
/// Legacy data contract for the old run configuration system. Should be deprecated
/// once no longer needed.
/// </summary>
public interface IRunConfig
{
    bool UseNonPublicizedAssemblies { get; }
    bool AutoGenerated { get; }
    bool UseInternalAssemblyName { get; }
    string Client { get; }
    string Server { get; }

    bool IsForced();
    bool IsStandard();
    bool IsForcedOrStandard();
}
