# yaml-language-server: $schema=https://json.schemastore.org/github-workflow.json

name: On push to a secondary branch

on:
  push:
    branches-ignore: ["master","lua-xpath-1.2.8","lua-xpath-1.2.8-preview"]
    paths-ignore:
      - ".github/**"
      - "*.md"

jobs:
  run-tests:
    uses: ./.github/workflows/run-tests.yml
    with:
      target: ${{ github.event.ref }}
